apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kp5f4ssf2-python
  janus-idp.io/tekton: kp5f4ssf2-python
  backstage.io/kubernetes-id: kp5f4ssf2-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kp5f4ssf2-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
